# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, abcnotation, lilypond, musicArticulation, musicDynamics
, musicDynamicsLiteral, musicParts, musicPitch, musicPitchLiteral
, musicPreludes, musicScore, musicxml2
}:

cabal.mkDerivation (self: {
  pname = "music-suite";
  version = "1.8";
  sha256 = "04xvs2vgmcm7czzg79jkk0wingysx1a2zpjw1lvbxanf7xcc2xx4";
  buildDepends = [
    abcnotation lilypond musicArticulation musicDynamics
    musicDynamicsLiteral musicParts musicPitch musicPitchLiteral
    musicPreludes musicScore musicxml2
  ];
  noHaddock = true;
  meta = {
    description = "A set of libraries for composition, analysis and manipulation of music";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
