# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, abcnotation, lilypond, musicArticulation, musicDynamics
, musicDynamicsLiteral, musicParts, musicPitch, musicPitchLiteral
, musicPreludes, musicScore, musicxml2
}:

cabal.mkDerivation (self: {
  pname = "music-suite";
  version = "1.8.1";
  sha256 = "14hhzmsq5m2h0qq3220xv1gg90sn69whmiysj3y0mw6rcm0zia0f";
  buildDepends = [
    abcnotation lilypond musicArticulation musicDynamics
    musicDynamicsLiteral musicParts musicPitch musicPitchLiteral
    musicPreludes musicScore musicxml2
  ];
  noHaddock = true;
  meta = {
    description = "A set of libraries for composition, analysis and manipulation of music";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
