# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, semigroups, vectorSpace }:

cabal.mkDerivation (self: {
  pname = "average";
  version = "0.6";
  sha256 = "0ag2jxhxap8wzdlb23zvly5y09k6kh134rwdxq6dqxlqwfwhsyc9";
  buildDepends = [ semigroups vectorSpace ];
  meta = {
    description = "An average (arithmetic mean) monoid";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
