# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, deepseq, extendedReals, hashable, HUnit, lattices
, QuickCheck, testFramework, testFrameworkHunit
, testFrameworkQuickcheck2, testFrameworkTh
}:

cabal.mkDerivation (self: {
  pname = "data-interval";
  version = "1.1.1";
  sha256 = "1j4571qla66ks9kbyy3pllfgygjmrjb6sn3wjnlnwzsdskdg5fxk";
  buildDepends = [ deepseq extendedReals hashable lattices ];
  testDepends = [
    HUnit QuickCheck testFramework testFrameworkHunit
    testFrameworkQuickcheck2 testFrameworkTh
  ];
  meta = {
    description = "Interval arithmetic for both open and closed intervals";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
