# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, async, average, filepath, lens, lilypond, monadplus
, musicArticulation, musicDynamics, musicDynamicsLiteral
, musicParts, musicPitch, musicPitchLiteral, musicScore, musicxml2
, optparseApplicative, semigroups, split, tasty, tastyGolden
, temporary, vectorSpace, vectorSpacePoints
}:

cabal.mkDerivation (self: {
  pname = "music-preludes";
  version = "1.8.1";
  sha256 = "0apqhv3658i7nrh40ksfxzbi21xvfaix1mm2m3bxid2plbm88qav";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    async average filepath lens lilypond monadplus musicArticulation
    musicDynamics musicDynamicsLiteral musicParts musicPitch
    musicPitchLiteral musicScore musicxml2 optparseApplicative
    semigroups split temporary vectorSpace vectorSpacePoints
  ];
  testDepends = [ tasty tastyGolden ];
  jailbreak = true;
  doCheck = false;
  meta = {
    description = "Some useful preludes for the Music Suite";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
