# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, async, average, dataDefault, filepath, lens
, lilypond, monadplus, musicArticulation, musicDynamics
, musicDynamicsLiteral, musicParts, musicPitch, musicPitchLiteral
, musicScore, musicxml2, optparseApplicative, semigroups, split
, tasty, tastyGolden, temporary, vectorSpace, vectorSpacePoints
}:

cabal.mkDerivation (self: {
  pname = "music-preludes";
  version = "1.8";
  sha256 = "01mpb8g0b43v475d7w9hndfxlbxcy3l4fabq330c91api26vzsxa";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson async average dataDefault filepath lens lilypond monadplus
    musicArticulation musicDynamics musicDynamicsLiteral musicParts
    musicPitch musicPitchLiteral musicScore musicxml2
    optparseApplicative semigroups split temporary vectorSpace
    vectorSpacePoints
  ];
  testDepends = [ tasty tastyGolden ];
  jailbreak = true;
  doCheck = false;
  meta = {
    description = "Some useful preludes for the Music Suite";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
