# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, nats, semigroups }:

cabal.mkDerivation (self: {
  pname = "positive";
  version = "0.4";
  sha256 = "0vj0gd7xln1xihf8dyrr2sm7zh5wg6qvfzy30nslwgvzyn4f14gv";
  buildDepends = [ nats semigroups ];
  meta = {
    description = "Positive integers";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
