# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, applicativeNumbers, newtype, ty, vectorSpace }:

cabal.mkDerivation (self: {
  pname = "type-unary";
  version = "0.2.16";
  sha256 = "1pn65smi07gwd4h46irjawh1dnjnizs9ag0cyv55i0mjg8plyzvj";
  buildDepends = [ applicativeNumbers newtype ty vectorSpace ];
  meta = {
    homepage = "https://github.com/conal/type-unary";
    description = "Type-level and typed unary natural numbers, inequality proofs, vectors";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
