# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, semigroups }:

cabal.mkDerivation (self: {
  pname = "music-pitch-literal";
  version = "1.8.1";
  sha256 = "11qjsxn10lrl3z7yi8h2likasy1g68ybbfzpnx03d01irl5kyzyf";
  buildDepends = [ semigroups ];
  meta = {
    description = "Overloaded pitch literals";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
