# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, semigroups }:

cabal.mkDerivation (self: {
  pname = "music-pitch-literal";
  version = "1.8";
  sha256 = "0l4iw993jm0azl2v62y6k7gfg85kqwlr48gz4fk2c2ag4v5adifg";
  buildDepends = [ semigroups ];
  meta = {
    description = "Overloaded pitch literals";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
