# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, adjunctions, aeson, average, bifunctors, colour, comonad
, contravariant, dataDefault, distributive, HCodecs, lens, lilypond
, monadplus, mtl, musicDynamicsLiteral, musicPitchLiteral
, musicxml2, nats, NumInstances, parsec, prettify, profunctors
, semigroups, transformers, transformersCompat, vectorSpace
, vectorSpacePoints, void
}:

cabal.mkDerivation (self: {
  pname = "music-score";
  version = "1.8";
  sha256 = "1j3xz1xbww4qp6vdr0qc72v23r0vjgyd0n2c7p4wckfbbc95rnyj";
  buildDepends = [
    adjunctions aeson average bifunctors colour comonad contravariant
    dataDefault distributive HCodecs lens lilypond monadplus mtl
    musicDynamicsLiteral musicPitchLiteral musicxml2 nats NumInstances
    parsec prettify profunctors semigroups transformers
    transformersCompat vectorSpace vectorSpacePoints void
  ];
  jailbreak = true;
  meta = {
    description = "Musical score and part representation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
