# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, adjunctions, aeson, average, bifunctors, colour, comonad
, contravariant, distributive, HCodecs, lens, lilypond, monadplus
, mtl, musicDynamicsLiteral, musicPitchLiteral, musicxml2, nats
, NumInstances, parsec, prettify, semigroups, transformers
, transformersCompat, vectorSpace, vectorSpacePoints
}:

cabal.mkDerivation (self: {
  pname = "music-score";
  version = "1.8.1";
  sha256 = "1bz93g4v69wkwsamjmgbdxwnv77nwrnvrahj180vjkfwj77f88hq";
  buildDepends = [
    adjunctions aeson average bifunctors colour comonad contravariant
    distributive HCodecs lens lilypond monadplus mtl
    musicDynamicsLiteral musicPitchLiteral musicxml2 nats NumInstances
    parsec prettify semigroups transformers transformersCompat
    vectorSpace vectorSpacePoints
  ];
  jailbreak = true;
  meta = {
    description = "Musical score and part representation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
