# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, semigroups }:

cabal.mkDerivation (self: {
  pname = "prettify";
  version = "1.0";
  sha256 = "18bwgz2cgkd6n9gwpwipv2bc6d5501mflmr0r2akwy98q2gb9qg8";
  buildDepends = [ semigroups ];
  meta = {
    description = "Haskell2010 structured text formatting";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
