# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, average, semigroups }:

cabal.mkDerivation (self: {
  pname = "music-articulation";
  version = "1.8";
  sha256 = "0inxmcrnpsxfgay1j7h45qwr45zq94l8pjfn0vwj7vmvhkymw5py";
  buildDepends = [ average semigroups ];
  meta = {
    description = "Abstract representation of musical articulation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
