# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataInterval, lens, musicPitchLiteral, nats, positive
, semigroups, typeUnary, vectorSpace, vectorSpacePoints
}:

cabal.mkDerivation (self: {
  pname = "music-pitch";
  version = "1.8";
  sha256 = "0q7v133p77sn2xwv2g14l1xzszzwqnfgs4k0rh4ckvzdphnlwvii";
  buildDepends = [
    dataInterval lens musicPitchLiteral nats positive semigroups
    typeUnary vectorSpace vectorSpacePoints
  ];
  jailbreak = true;
  meta = {
    description = "Musical pitch representation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
