# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "ty";
  version = "0.1.6";
  sha256 = "0i18c293f6dz7qgr5z4x6rzndhqv5q7myw1wvs8i9ld23d87fjhy";
  meta = {
    homepage = "https://github.com/conal/ty";
    description = "Typed type representations and equality proofs";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
