# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefault, musicDynamicsLiteral, musicPitchLiteral, nats
, reverseApply, semigroups, typeUnary, xml
}:

cabal.mkDerivation (self: {
  pname = "musicxml2";
  version = "1.8.1";
  sha256 = "096vm73a4ngl1yc27x7z226difh97zjm5386cy5vw58ndmf1fws7";
  buildDepends = [
    dataDefault musicDynamicsLiteral musicPitchLiteral nats
    reverseApply semigroups typeUnary xml
  ];
  meta = {
    description = "A representation of the MusicXML format";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
