# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, baseUnicodeSymbols, text }:

cabal.mkDerivation (self: {
  pname = "roman-numerals";
  version = "0.5.1.5";
  sha256 = "10da5vls9l5i255bapms4b2r7dnwmxgsaa1cdll2lrmid5dikixr";
  buildDepends = [ baseUnicodeSymbols text ];
  meta = {
    homepage = "https://github.com/roelvandijk/roman-numerals";
    description = "Parsing and pretty printing of Roman numerals";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
