# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, parsec, prettify, semigroups }:

cabal.mkDerivation (self: {
  pname = "abcnotation";
  version = "1.8";
  sha256 = "1j0j2wzn7fr0n3gbcdf531wr5sg7xmrmbm221j5pni9nlqm2hr7x";
  buildDepends = [ parsec prettify semigroups ];
  meta = {
    description = "Haskell representation and parser for ABC notation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
