# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, parsec, prettify, semigroups }:

cabal.mkDerivation (self: {
  pname = "abcnotation";
  version = "1.8.1";
  sha256 = "18qb8qdlfi3r8vv8aagsz65iv2clyj9lzn0q29m4gpvzgncsn22n";
  buildDepends = [ parsec prettify semigroups ];
  meta = {
    description = "Haskell representation and parser for ABC notation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
