# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, adjunctions, aeson, dataDefault, lens, musicDynamics
, musicPitch, romanNumerals, semigroups
}:

cabal.mkDerivation (self: {
  pname = "music-parts";
  version = "1.8";
  sha256 = "0mb07c4494dxdvzsyi06znnha65llpgy08hf6wfrsl14nizpasfl";
  buildDepends = [
    adjunctions aeson dataDefault lens musicDynamics musicPitch
    romanNumerals semigroups
  ];
  jailbreak = true;
  meta = {
    description = "Musical instruments, parts and playing techniques";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
