# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, semigroups }:

cabal.mkDerivation (self: {
  pname = "music-dynamics-literal";
  version = "1.8";
  sha256 = "1rgir9r12jrc73g1rsnl9ksqzr2yh7pyha13ih94lskcqc2zvqps";
  buildDepends = [ semigroups ];
  meta = {
    description = "Overloaded dynamics literals";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
