# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, semigroups }:

cabal.mkDerivation (self: {
  pname = "music-dynamics-literal";
  version = "1.8.1";
  sha256 = "1p5r9fj71rvg2hma1r4s4vlxxqzam7iq99hfmn8k92sv7yzjm5na";
  buildDepends = [ semigroups ];
  meta = {
    description = "Overloaded dynamics literals";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
