# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefault, musicDynamicsLiteral, musicPitchLiteral
, prettify, semigroups, vectorSpace
}:

cabal.mkDerivation (self: {
  pname = "lilypond";
  version = "1.8";
  sha256 = "188m2qvv3l30wdhl634dkqvbwxan2dab7ip6cwp5kx5rv19q6sm6";
  buildDepends = [
    dataDefault musicDynamicsLiteral musicPitchLiteral prettify
    semigroups vectorSpace
  ];
  meta = {
    description = "Bindings to Lilypond";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
