# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, average, musicDynamicsLiteral, semigroups }:

cabal.mkDerivation (self: {
  pname = "music-dynamics";
  version = "1.8.1";
  sha256 = "1rdv9kn3i5m6l9xpfmccdwjkdw0smr9qiaw4p0y79fr9gdqrd6a1";
  buildDepends = [ average musicDynamicsLiteral semigroups ];
  meta = {
    description = "Abstract representation of musical dynamics";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
