# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "applicative-numbers";
  version = "0.1.3";
  sha256 = "0rnjl7yz6nga4qi0jdvhf911yf1qk6gy2fm5236bsgc50d5wbaw0";
  meta = {
    homepage = "http://haskell.org/haskellwiki/applicative-numbers";
    description = "Applicative-based numeric instances";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
    maintainers = with self.stdenv.lib.maintainers; [ meditans ];
  };
})
